jasypt:
  encryptor:
    bean: stringEncryptor

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/modac
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      location: /home/ubuntu/contents

hibernate.id.new_generator_mappings: true
