jasypt:
  encryptor:
    bean: stringEncryptor

spring:
  datasource:
    url: ENC(7wwBf4+5o0+obCrm1EkPxSdgpZscW07fg4L4OiQqcjAOE4wyl8FWxiPTIJdcEgohuAcS7LQ/ZJvwhBsgj/fJqm3kJ68/64cYhWRX2OLVXdtdZgA934mgVQ==)
    username: ENC(4yvZaZZv6EFw2t1ooxl8rQ==)
    password: ENC(910Xyq/MceipjhuVJ3J04ao4GbgJ4aHg)
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      location: /Users/mingu/Projects/modac/contents

hibernate.id.new_generator_mappings: true
