jasypt:
  encryptor:
    bean: stringEncryptor

spring:
  datasource:
    url: ENC(IPQ1oBwUZmcqJM8lm12BrsyjFnp+Xnn0wknw70pdiJE5IfKUGOwTUY5dxkgYpiOF)
    username: ENC(0bBUEz+4A+KmIpUJM4pb9A==)
    password: ENC(Ix2gKEu3P0qEnnP0AKzI2A==)
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      location: /Users/mingu/Projects/modac/contents

hibernate.id.new_generator_mappings: true
